game/urls.py
from django.urls import path
from .views import (
    GridCreateView,
    HiddenGridDetailView,
    VisibleGridDetailView,
    GridDeleteView,
    grid_regenerate,
)

app_name = "game"

urlpatterns = [
    path("", GridCreateView.as_view(), name="grid-form"),
    path("<uuid:pk>/", HiddenGridDetailView.as_view(), name="grid-detail-hidden"),
    path(
        "<uuid:pk>/visible", VisibleGridDetailView.as_view(), name="grid-detail-visible"
    ),
    path("<uuid:pk>/delete", GridDeleteView.as_view(), name="grid-delete"),
    path("<uuid:pk>/regenerate-grid", grid_regenerate, name="grid-regenerate"),
]

game/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.core.exceptions import ValidationError
from django.db.models import Q
import logging
import random
import uuid

logger = logging.getLogger("__name__")

MAX_PLACEMENT_TRY = 500

NB_CRUISER = 1
NB_ESCORTSHIP = 2
NB_TORPEDOBOAT = 3
NB_SUBMARINE = 4


# Create your models here.
class Grid(models.Model):
    class Cell(models.TextChoices):
        WATER = "~", "Water"
        SHIP = "S", "Ship"
        SHIP_SAFE_SPACE = "-", "Ship safe space"
        SHOT_SUCCESS = "X", "Success shot"
        SHOT_MISS = "O", "Miss shot"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nb_columns = models.PositiveSmallIntegerField(
        default=8, validators=[MinValueValidator(8)], verbose_name="Number of columns"
    )  # x Axis
    nb_rows = models.PositiveSmallIntegerField(
        default=8, validators=[MinValueValidator(8)], verbose_name="Number of rows"
    )  # y Axis
    created_at = models.DateTimeField(auto_now_add=True)

    def place_ships_randomly(self, nb_max_attempt=MAX_PLACEMENT_TRY, **kwargs):
        """
        Place the ships randomly in the grid
        :param nb_max_attempt: Number of max attemp to place the ships in the grid
        :return:
        """
        nb_attempt = 0
        impossible_placement = True

        # Trying multiple time to place all the ships in the grid
        # When the grid is small, many attempts can be needed
        while impossible_placement and nb_attempt < nb_max_attempt:
            # For now, the placement is possible
            impossible_placement = False
            # For each attempt, a fresh grid is generated
            temp_grid = self.empty_grid()
            # Ships that have been successfully placed are stored in a list
            # in order to limit useless database requests
            ships_to_be_created = []

            ships_to_be_placed = kwargs.get("ships_list", self.ships_to_be_placed())

            # Trying to place each ship individually in the grid
            for ship_to_be_placed in ships_to_be_placed:
                try:
                    # If the ship can be placed, a Ship object is returned
                    # The Ship object contain the location
                    ship_to_be_created = self.place_ship_randomly(
                        temp_grid, ship_to_be_placed
                    )
                except ValueError:
                    # If the ship can't be placed, a ValueError is raised
                    nb_attempt += 1
                    impossible_placement = True
                    break
                # If the ship have successfully been placed, he's added to the temporary grid
                # to prevent other ship to be placed at the same location
                temp_grid = self.add_ship_to_grid(temp_grid, ship_to_be_created)
                # The ship is also added to the ship object lists to be created
                # if all ships can be placed
                ships_to_be_created.append(ship_to_be_created)

            # If all ship can be placed, every ship object is created
            if not impossible_placement:
                Ship.objects.bulk_create(ships_to_be_created)
                break

    def place_ship_randomly(self, temp_grid, ship_size):
        """
        If the ship can be placed, return a Ship object that contain a possible ship location's in the grid
        :return:
        """
        # List the available cells of the grid
        available_cells = [
            (row_index, cell_index)
            for (row_index, row) in enumerate(temp_grid)
            for (cell_index, cell) in enumerate(row)
            if cell == Grid.Cell.WATER
        ]
        # Try different location while there is enough
        # available cells to place the ship
        while len(available_cells) >= ship_size:
            # Choose a random cell from the available ones
            origin_cell = random.choice(available_cells)
            # For each cell, both vertical and horizontal orientation will be tested
            orientations = Ship.Orientation.choices
            random.shuffle(orientations)
            # Test both orientation in a random order
            for orientation in orientations:
                if self.ship_can_be_placed(
                    temp_grid, origin_cell, orientation, ship_size
                ):
                    # The ship can be placed here
                    # A Ship object that contain the location is returned
                    return Ship(
                        grid=self,
                        x=origin_cell[1],
                        y=origin_cell[0],
                        orientation=orientation[0],
                        ship_size=ship_size,
                    )
            # The ship can't be placed here
            # The tested cell is removed from available cells
            available_cells.remove(origin_cell)
        raise ValueError("The ship can't be placed")

    def ship_can_be_placed(self, grid, location, orientation, ship_size):
        """
        Return true if the ship can be placed at this location
        :return: bool : True if the ship can be placed at this location
        """
        if orientation[0] == Ship.Orientation.HORIZONTAL:
            for cell_x_axis in range(ship_size):
                if location[1] + cell_x_axis >= self.nb_columns:
                    return False
                if grid[location[0]][location[1] + cell_x_axis] != Grid.Cell.WATER:
                    return False
        else:
            for cell_y_axis in range(ship_size):
                if location[0] + cell_y_axis >= self.nb_rows:
                    return False
                if grid[location[0] + cell_y_axis][location[1]] != Grid.Cell.WATER:
                    return False
        return True

    @staticmethod
    def ships_to_be_placed(**kwargs):
        """
        Return a ship type list to be placed in the grid
        :return: list[Ship.Size]
        """
        ships_list = []

        ships_list.extend(
            [Ship.Size.CRUISER for _ in range(kwargs.get("nb_cruiser", NB_CRUISER))]
            + [
                Ship.Size.ESCORTSHIP
                for _ in range(kwargs.get("nb_escortship", NB_ESCORTSHIP))
            ]
            + [
                Ship.Size.TORPEDOBOAT
                for _ in range(kwargs.get("nb_torpedoboat", NB_TORPEDOBOAT))
            ]
            + [
                Ship.Size.SUBMARINE
                for _ in range(kwargs.get("nb_submarine", NB_SUBMARINE))
            ]
        )
        random.shuffle(ships_list)
        return ships_list

    def regenerate_grid(self, **kwargs):
        """
        Remove all shots and ships from the grid, then place new ships randomly
        """
        # Remove all shots
        self.shots.all().delete()
        # Remove all ships
        self.ships.all().delete()
        # Place new ships randomly
        if "ships_list" in kwargs:
            self.place_ships_randomly(ships_list=kwargs.get("ships_list"))
        else:
            self.place_ships_randomly()

    @property
    def visible_grid(self):
        """
        Return a grid with headers where all cells are visible
        :return: list[list[Cell]] : representing the grid with headers
        """
        # Get the grid
        grid_to_return = self.grid
        # Add headers to grid
        grid_to_return = self.add_headers(grid_to_return)
        return grid_to_return

    @property
    def hidden_grid(self):
        """
        Return a grid with headers where ships and ships safe spaces are hidden
        :return: list[list[Cell]] : representing the grid with headers
        """
        # Get the grid
        grid_to_return = self.grid
        # Check each grid rows
        for row_index in range(len(grid_to_return)):
            for cell_index in range(len(grid_to_return[row_index])):
                if grid_to_return[row_index][cell_index] in (
                    Grid.Cell.SHIP,
                    Grid.Cell.SHIP_SAFE_SPACE,
                ):
                    grid_to_return[row_index][cell_index] = Grid.Cell.WATER
        # Add headers to grid
        grid_to_return = self.add_headers(grid_to_return)
        return grid_to_return

    @property
    def grid(self):
        """
        Return a grid with all cells visible
        :return: list[list[Cell]] : representing the grid
        """
        # Start with an empty grid
        grid = self.empty_grid()

        # Add all ships to the grid
        for ship in self.ships.all():
            self.add_ship_to_grid(grid, ship)

        # Add all shots to the grid
        for shot in self.shots.all():
            self.add_shot_to_grid(grid, shot)

        # Return the grid with ships and shots
        return grid

    @property
    def is_game_over(self):
        """
        Return true if all the ships are sunk
        :return: bool : True if all the ships are sunk
        """
        if self.ships.all().exists():
            for ship in self.ships.all():
                if not ship.is_sunk:
                    return False
            return True
        else:
            return False

    @property
    def nb_sunken_ships(self):
        """
        Return the number of sunken ships
        :return: int : Number of sunken ships
        """
        nb_sunken_ships = 0
        for ship in self.ships.all():
            if ship.is_sunk:
                nb_sunken_ships += 1
        return nb_sunken_ships

    @property
    def nb_remaining_ships(self):
        """
        Return the number of remaining ships
        :return: int : Number of remaining ships
        """
        nb_remaining_ships = 0
        for ship in self.ships.all():
            if not ship.is_sunk:
                nb_remaining_ships += 1
        return nb_remaining_ships

    def add_headers(self, grid):
        """
        Add headers to the grid passed in param

game/forms.py
from django import forms

from .models import Shot


class ShotForm(forms.ModelForm):
    class Meta:
        model = Shot
        fields = (
            "grid",
            "x",
            "y",
        )
        widgets = {"grid": forms.HiddenInput()}

game/views.py
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormMixin
from django.views.decorators.http import require_http_methods
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.shortcuts import reverse
from django.urls import reverse_lazy
from .models import Grid
from .forms import ShotForm
from django.http import Http404


# Create your views here.
class GridCreateView(CreateView):
    """
    Allows the creation of a new Grid and see the list of grid already created
    """

    model = Grid
    fields = ["nb_rows", "nb_columns"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add grid history to context
        context["grid_history"] = Grid.objects.all()
        return context

    def get_success_url(self):
        # If the grid is created successfully, redirect to the grid page
        return reverse("game:grid-detail-hidden", args=(self.object.id,))


class GridDeleteView(DeleteView):
    """
    Allows to delete a grid, then redirect to the creation grid page
    """

    model = Grid
    success_url = reverse_lazy("game:grid-form")


class GridDetailView(FormMixin, DetailView):
    """
    Only used by HiddenGridDetailView and VisibleGridDetailView !
    Allow to see the grid and shoot
    """

    model = Grid
    form_class = ShotForm

    def get_object(self, queryset=None):
        # Get the grid that match the UUID in the url
        try:
            my_grid = Grid.objects.get(id=self.kwargs.get("pk"))
            return my_grid
        except self.model.DoesNotExist:
            raise Http404("No grid matches the given query.")

    def get_initial(self):
        # Fill the 'grid' field of the ShotForm
        return {"grid": self.object}

    def post(self, request, *args, **kwargs):
        # Validation of the ShotForm
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class HiddenGridDetailView(GridDetailView):
    """
    Inherits from GridDetailView
    Display a hidden grid, only water and shot are visible
    """

    template_name = "game/grid_detail_hidden.html"

    def get_success_url(self):
        return reverse("game:grid-detail-hidden", args={self.object.id})

    def form_valid(self, form):
        the_shot = form.save()
        if the_shot.is_successful:
            hit_ship = the_shot.hit_ship
            if hit_ship.is_sunk:
                messages.success(self.request, "You sunk a ship !")
        return super(HiddenGridDetailView, self).form_valid(form)


class VisibleGridDetailView(GridDetailView):
    """
    Inherits from GridDetailView
    Display a visible grid (ships and ships safe space are visible)
    Display a detailed ships list
    """

    template_name = "game/grid_detail_visible.html"

    def get_success_url(self):
        return reverse("game:grid-detail-visible", args={self.object.id})

    def form_valid(self, form):
        the_shot = form.save()
        if the_shot.is_successful:
            hit_ship = the_shot.hit_ship
            if hit_ship.is_sunk:
                messages.success(self.request, "You sunk a ship !")
        return super(VisibleGridDetailView, self).form_valid(form)


@require_http_methods(["GET"])
def grid_regenerate(request, pk):
    """
    Allow to (re)generate ships placement
    :param request:
    :param pk: UUID : grid's UUID
    :return: redirect to HiddenGridDetailView
    """
    grid = get_object_or_404(Grid, id=pk)
    grid.regenerate_grid()
    return HttpResponseRedirect(reverse("game:grid-detail-hidden", args=(pk,)))

game/templates/game/base.html
{% extends 'base.html' %}

{% block body %}
    Game base template
{% endblock body %}

game/templates/game/grid_confirm_delete.html
{% extends 'game/base.html' %}

{% block body %}
    <main class="container mt-5">
        <div class="bg-light p-5 rounded">
            <h1>Confirm deletion ?</h1>
            <form method="post">{% csrf_token %}
                <p class="lead">Are you sure you want to delete "{{ object }}"?</p>
                {{ form }}
                <input type="submit" class="btn btn-danger" value="Confirm">
                <a href="{% url 'game:grid-detail-hidden' object.id %}" class="btn btn-primary">Cancel</a>
            </form>
        </div>
    </main>
{% endblock body %}

game/templates/game/grid_detail_hidden.html
{% extends 'game/base.html' %}

{% block body %}
    <div class="bg-light">
        <div class="container pb-3 bg-light">
            <h1 class="display-3">Warship</h1>
            <a href="{% url 'game:grid-form' %}" type="button" class="btn btn-outline-primary mr-3">Back</a>
            <a href="{% url 'game:grid-detail-visible' object.id %}" type="button" class="btn btn-outline-primary mr-3">Make ship visible</a>
            <a href="{% url 'game:grid-regenerate' object.id %}" type="button" class="btn btn-outline-primary mr-3">(Re)generate ships</a>
            <a href="{% url 'game:grid-delete' object.id %}" type="button" class="btn btn-outline-danger mr-3">Delete this grid</a>
        </div>
    </div>
    {% include "game/components/game_over_alert.html" %}
    {% include "game/components/no_ship_alert.html" %}

    <div class="row text-center">
        <div class="col-md-3">
            <h3>Shot history</h3>
        </div>
        <div class="col-md-6">
            <h3>The grid</h3>
            <p>
                <strong>{{ object.nb_sunken_ships }}</strong> ships were sunk -
                <strong>{{ object.nb_remaining_ships }}</strong> ships remaining
            </p>
        </div>
        <div class="col-md-3">
            <h3>Shot form</h3>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-md-3">
            {% include "game/components/shots_history.html" %}
        </div>
        <div class="col-md-6">
            {% include "game/components/messages.html" %}
            {% include "game/components/grid_table.html" with grid=object.hidden_grid %}
            {% include "game/components/grid_table_legend.html" with full_legend=False %}
        </div>
        <div class="col-md-3">
            {% include "game/components/shot_form.html" %}
        </div>
    </div>
{% endblock body %}

game/templates/game/grid_detail_visible.html
{% extends 'game/base.html' %}

{% block body %}
    <div class="bg-light">
        <div class="container pb-3 bg-light">
            <h1 class="display-3">Warship</h1>
            <a href="{% url 'game:grid-form' %}" type="button" class="btn btn-outline-primary mr-3">Back</a>
            <a href="{% url 'game:grid-detail-hidden' object.id %}" type="button" class="btn btn-primary mr-3">Make ship hidden</a>
            <a href="{% url 'game:grid-regenerate' object.id %}" type="button" class="btn btn-outline-primary mr-3">(Re)generate ships</a>
            <a href="{% url 'game:grid-delete' object.id %}" type="button" class="btn btn-outline-danger mr-3">Delete this grid</a>
        </div>
    </div>
    {% include "game/components/game_over_alert.html" %}
    {% include "game/components/no_ship_alert.html" %}

    <div class="row text-center">
        <div class="col-md-3">
            <h3>Shot history</h3>
        </div>
        <div class="col-md-6">
            <h3>The grid</h3>
            <p>
                <strong>{{ object.nb_sunken_ships }}</strong> ships were sunk -
                <strong>{{ object.nb_remaining_ships }}</strong> ships remaining
            </p>
        </div>
        <div class="col-md-3">
            <h3>Shot form</h3>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-md-3">
            {% include "game/components/shots_history.html" %}
        </div>
        <div class="col-md-6">
            {% include "game/components/messages.html" %}
            {% include "game/components/grid_table.html" with grid=object.visible_grid %}
            {% include "game/components/grid_table_legend.html" with full_legend=True %}
        </div>
        <div class="col-md-3">
            {% include "game/components/shot_form.html" %}
            <h3 class="mt-5">Ship locations</h3>
            {% include "game/components/ships_list.html" %}
        </div>
    </div>
{% endblock body %}

game/templates/game/grid_form.html
{% extends 'game/base.html' %}

{% block body %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Warship</h1>
    </div>
    <div class="container" style="max-width: 500px">
        <div class="card">
            <div class="card-body text-center">
                <h5 class="card-title">Create a new grid</h5>
                {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for field in form %}
                            {% for error in field.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        {% endfor %}
                    </div>
                {% endif %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error|escape }}
                    </div>
                {% endfor %}
                <div style="max-width: 500px">
                    <form method="post">{% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row mb-2">
                                <label for="{{ field.id_for_label }}" class="col-sm-5 col-form-label">{{ field.label }}</label>
                                <div class="col-sm-7">
                                    <input type="number" class="form-control" id="{{ field.id_for_label }}" name="{{ field.name }}" value="{{ field.value }}" required>
                                </div>
                            </div>
                        {% endfor %}
                        <input type="submit" class="btn btn-primary" value="Create">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-5">
        <div class="table-responsive">
            <table class="table table-striped table-sm" aria-hidden="true">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Status</th>
                        <th>Nb columns</th>
                        <th>Nb rows</th>
                        <th>Created at</th>
                    </tr>
                </thead>
                <tbody>
                    {% for grid in grid_history %}
                        <tr>
                            <td><a href="{% url 'game:grid-detail-hidden' grid.id %}">{{ grid.id }}</a></td>
                            <td>
                                {% if grid.is_game_over == True %}
                                    Over
                                {% else %}
                                    Ongoing
                                {% endif %}
                            </td>
                            <td>{{ grid.nb_columns }}</td>
                            <td>{{ grid.nb_rows }}</td>
                            <td>{{ grid.created_at }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5" class="text-center">No grid have been created yet.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock body %}